### ISSUE TITLE
V. 11 seems to have broken the import

### ISSUE THREAD

**Issue by MrAlbertShiny** [dmarcuse/fvtt-adventure-bundler#8]
Hi,

I was able with the module to export stuff from one word.
But: The Import-Button is something I cannot find in another world with the activated module.
The Import-Button should be somewhere at the adventure, or? I cannot find it there:

![grafik](https://github.com/dmarcuse/fvtt-adventure-bundler/assets/136933623/e6a652f2-0c77-4bfb-a4ad-8022ea518c8e)

Or I'm completely on the wrong way where the buttons should pop up.

With best regards,
Jens

**Comment by dmarcuse** [comment]
Yep, it should be there - I haven't started work on updating to V11 just yet, but I should have some time for that this week. Thanks for the report!

**Comment by dmarcuse** [comment]
Alright, this has been fixed in version 0.2.3, which I'm releasing now. I've encountered a new issue where importing occasionally fails in v11 which I'm still diagnosing, so it's not perfect, but it's at least usable now.

**Comment by icen1** [comment]
![2024-03-30_22-17](https://github.com/dmarcuse/fvtt-adventure-bundler/assets/29306674/822bd8db-3477-41ca-9af5-d789c20986db)
@dmarcuse Hi, Are you sure this has been fixed? I installed the newest version using the link in the README (version being 0.23) but for some reason i still can't find the button

**Comment by dmarcuse** [comment]
@icen1, it seems to be working correctly for me on Foundry V11 build 315, with version 0.2.3 of the module. Could you perform some troubleshooting steps?

- Double check that the module is enabled in the world you're using
- Try temporarily disabling other modules to check for a conflict, particularly if they alter the UI
- Check for any messages in the browser console (you can usually access this by pressing F12 and then selecting the console tab)
- Let me know the Foundry version and game system you're using - I have not tested against Foundry V12 builds yet, which are in a prototype state and not intended for general use yet

![image](https://github.com/dmarcuse/fvtt-adventure-bundler/assets/5429337/0b70e44a-a657-412a-9c22-e18c1f7f2c22)
